"use client";

import { Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useCart } from "./cart-provider";
import { formatPrice } from "@/lib/format";

export function CartPage() {
  const { items, subtotal, updateQuantity, removeItem } = useCart();
  if (!items.length) return <div className="container-shell flex min-h-[55vh] flex-col items-center justify-center py-16 text-center"><div className="rounded-full bg-stone-100 p-6"><ShoppingBag size={35} className="text-stone-400" /></div><h1 className="display-title mt-6 text-4xl">Your bag is empty</h1><p className="mt-3 text-sm text-stone-500">Looks like you haven’t added anything yet.</p><Link href="/products" className="button-primary mt-7">Start shopping</Link></div>;
  return <div className="container-shell py-9 sm:py-12"><h1 className="display-title text-4xl sm:text-5xl">Shopping bag <span className="text-xl text-stone-400">({items.length})</span></h1><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_380px]">
    <div className="divide-y divide-stone-200 border-y border-stone-200">{items.map((item) => <article key={item.id} className="grid grid-cols-[92px_1fr] gap-4 py-5 sm:grid-cols-[120px_1fr_auto] sm:gap-6"><Link href={`/products/${item.slug}`} className="relative aspect-[4/5] overflow-hidden bg-stone-100"><Image src={item.image} alt={item.title} fill sizes="120px" className="object-cover" /></Link><div><p className="text-[10px] font-bold uppercase tracking-wider text-stone-400">SKU: {item.sku}</p><Link href={`/products/${item.slug}`} className="mt-1 block font-bold leading-5">{item.title}</Link>{item.variantTitle && <p className="mt-1 text-xs text-stone-500">Option: {item.variantTitle}</p>}<p className="mt-3 font-bold text-[#6f2742] sm:hidden">{formatPrice(item.price * item.quantity)}</p><div className="mt-4 flex items-center gap-4"><div className="flex h-9 items-center border border-stone-300"><button onClick={() => updateQuantity(item.id, item.quantity - 1)} className="flex h-full w-9 items-center justify-center" aria-label="Decrease"><Minus size={14} /></button><span className="w-7 text-center text-xs font-bold">{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)} className="flex h-full w-9 items-center justify-center" aria-label="Increase"><Plus size={14} /></button></div><button onClick={() => removeItem(item.id)} className="flex items-center gap-1 text-xs font-semibold text-stone-500 hover:text-red-600"><Trash2 size={14} /> Remove</button></div></div><div className="hidden text-right sm:block"><p className="font-bold text-[#6f2742]">{formatPrice(item.price * item.quantity)}</p><p className="mt-1 text-xs text-stone-400">{formatPrice(item.price)} each</p></div></article>)}</div>
    <aside className="card h-fit bg-[#f7f4f3] p-6 lg:sticky lg:top-28"><h2 className="display-title text-2xl">Order summary</h2><div className="mt-6 space-y-3 border-b border-stone-200 pb-5 text-sm"><div className="flex justify-between"><span className="text-stone-600">Subtotal</span><strong>{formatPrice(subtotal)}</strong></div><div className="flex justify-between"><span className="text-stone-600">Delivery</span><span>Calculated at checkout</span></div></div><div className="flex justify-between py-5 text-lg"><strong>Total</strong><strong>{formatPrice(subtotal)}</strong></div><Link href="/checkout" className="button-primary w-full">Proceed to checkout</Link><Link href="/products" className="mt-3 block text-center text-xs font-bold underline">Continue shopping</Link></aside>
  </div></div>;
}
