"use client";

import { ArrowRight, LoaderCircle, LogOut, Package, UserRound } from "lucide-react";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";
import { formatPrice } from "@/lib/format";
import { createSupabaseBrowserClient, hasSupabaseConfig } from "@/lib/supabase/client";

type LocalOrder = { orderNumber: string; createdAt: string; total: number; orderStatus: string; paymentStatus: string };
export function AccountPortal() {
  const [orders, setOrders] = useState<LocalOrder[]>([]); const [userEmail, setUserEmail] = useState<string | null>(null); const [loading, setLoading] = useState(hasSupabaseConfig); const [mode, setMode] = useState<"login" | "signup">("login");
  useEffect(() => { setOrders(JSON.parse(localStorage.getItem("burmese-house-orders-v1") || "[]") as LocalOrder[]); const supabase = createSupabaseBrowserClient(); if (!supabase) return; supabase.auth.getUser().then(({ data }) => { setUserEmail(data.user?.email ?? null); setLoading(false); }); }, []);
  const authenticate = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const supabase = createSupabaseBrowserClient(); if (!supabase) return; const data = new FormData(event.currentTarget); const email = String(data.get("email")); const password = String(data.get("password")); setLoading(true); const result = mode === "login" ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password }); setLoading(false); if (result.error) return toast.error(result.error.message); if (mode === "signup" && !result.data.session) return toast.success("Check your email to confirm your account"); setUserEmail(result.data.user?.email ?? email); toast.success(mode === "login" ? "Login successful" : "Account created"); };
  const logout = async () => { await createSupabaseBrowserClient()?.auth.signOut(); setUserEmail(null); toast.success("Signed out"); };
  if (loading) return <div className="flex min-h-60 items-center justify-center"><LoaderCircle className="animate-spin" /></div>;
  if (hasSupabaseConfig && !userEmail) return <div className="container-shell max-w-md py-12"><div className="card p-6 sm:p-8"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-[#f3e8ec] text-[#6f2742]"><UserRound /></div><h1 className="display-title mt-5 text-center text-3xl">{mode === "login" ? "Welcome back" : "Create your account"}</h1><p className="mt-2 text-center text-sm text-stone-500">{mode === "login" ? "Sign in to see orders and saved details." : "Checkout faster and keep your order history together."}</p><form onSubmit={authenticate} className="mt-7 space-y-4"><label className="block"><span className="label">Email address</span><input name="email" type="email" required className="field" /></label><label className="block"><span className="label">Password</span><input name="password" type="password" minLength={8} required className="field" /></label><button className="button-primary w-full">{mode === "login" ? "Sign in" : "Create account"}</button></form><button onClick={() => setMode(mode === "login" ? "signup" : "login")} className="mt-5 w-full text-center text-xs font-bold text-[#6f2742]">{mode === "login" ? "New here? Create an account" : "Already have an account? Sign in"}</button><p className="mt-6 text-center text-[11px] text-stone-400">Guest checkout is always available.</p></div></div>;
  return <div className="container-shell py-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">My account</p><h1 className="display-title mt-2 text-4xl">Hello{userEmail ? `, ${userEmail.split("@")[0]}` : " there"}.</h1><p className="mt-2 text-sm text-stone-500">Manage orders and your shopping details.</p></div>{userEmail && <button onClick={logout} className="flex items-center gap-2 text-sm font-bold"><LogOut size={16} /> Sign out</button>}</div>{!hasSupabaseConfig && <div className="mt-6 border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-800">Demo account mode is active. Add Supabase variables to enable secure sign-up and login. Guest orders placed on this device still appear below.</div>}<div className="mt-8 grid gap-4 sm:grid-cols-3"><AccountCard href="/account/orders" icon={<Package />} title="Orders" detail={`${orders.length} order${orders.length === 1 ? "" : "s"}`} /><AccountCard href="/account/profile" icon={<UserRound />} title="Profile" detail="Personal information" /><AccountCard href="/account/addresses" icon={<ArrowRight />} title="Addresses" detail="Saved delivery details" /></div><div className="mt-10"><div className="flex items-center justify-between"><h2 className="display-title text-2xl">Recent orders</h2><Link href="/account/orders" className="text-xs font-bold text-[#6f2742]">View all</Link></div>{orders.length ? <div className="mt-4 overflow-x-auto border border-stone-200"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase text-stone-500"><tr><th className="p-4">Order</th><th>Date</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{orders.slice(0, 5).map((order) => <tr key={order.orderNumber} className="border-t border-stone-200"><td className="p-4 font-bold">{order.orderNumber}</td><td>{new Date(order.createdAt).toLocaleDateString("en-BD")}</td><td>{formatPrice(order.total)}</td><td className="capitalize">{order.orderStatus}</td><td><Link href={`/account/orders/${order.orderNumber}`} className="font-bold text-[#6f2742]">View</Link></td></tr>)}</tbody></table></div> : <div className="card mt-4 py-10 text-center text-sm text-stone-500">No orders on this device yet. <Link href="/products" className="font-bold text-[#6f2742]">Start shopping</Link></div>}</div></div>;
}
function AccountCard({ href, icon, title, detail }: { href: string; icon: React.ReactNode; title: string; detail: string }) { return <Link href={href} className="card flex items-center gap-4 p-5 transition hover:border-[#6f2742]"><span className="flex h-10 w-10 items-center justify-center bg-[#f3e8ec] text-[#6f2742]">{icon}</span><span><strong className="block">{title}</strong><span className="text-xs text-stone-500">{detail}</span></span></Link>; }
